spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    #url: jdbc:sqlserver://localhost:1433;databaseName=jpashop;encrypt=true;trustServerCertificate=true;
    url: jdbc:sqlserver://61.83.139.234:1433;DatabaseName=jpashop;encrypt=true;trustServerCertificate=true;
    username: mssqlUser
    password: mmj1213!@

  jpa:
    hibernate:

      ddl-auto: create        # ???? ??? ? ??? ?? ??
    properties:
      hibernate:
#        show_sql: true         System.out? ??? ??? ??
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug  # logger? ??? ??? ??